#!/bin/bash


export DEST=172.16.120.130
case "$1" in
  build)
	tar -czvf flask_hello.tar.gz flask_hello
	;;
  test_connection)
	ssh root@$DEST exit
	if [[ $? == 0 ]]; then
		echo "Connection OK"
		exit 0
	else
		echo "Connection FAIL"
		exit 255
	fi
esac
