---


- name: Installing req for Docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2


- name: Add docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Installing Docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce